spring.application.name=hospital-management
spring.datasource.url=${DB_URL}
spring.datasource.username=${root}
spring.datasource.password=${Kolhe%456@Bk}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}
